# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=release
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),release)
  GlobalIllumination_config = release
endif
ifeq ($(config),debug)
  GlobalIllumination_config = debug
endif

PROJECTS := GlobalIllumination

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

GlobalIllumination:
ifneq (,$(GlobalIllumination_config))
	@echo "==== Building GlobalIllumination ($(GlobalIllumination_config)) ===="
	@${MAKE} --no-print-directory -C LiVHY -f Makefile config=$(GlobalIllumination_config)
endif

clean:
	@${MAKE} --no-print-directory -C LiVHY -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  release"
	@echo "  debug"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GlobalIllumination"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"